### ISSUE TITLE
Не хватает данных

### ISSUE THREAD

**Issue by skabbit** [igor35hh/declarator#1]
Для проверки тестового задания нам нужно его запустить. Полезно иметь requirements.txt и версию питона, которая была использована.
Дополните репозиторий и напишите инструкцию в readme.
Спасибо.

**Comment by igor35hh** [comment]
Добавил requirements.txt, написал  инструкцию в readme, настроил запуск в докере с демо данными и пользователем админ.

**Comment by igor35hh** [comment]
> Для проверки тестового задания нам нужно его запустить. Полезно иметь requirements.txt и версию питона, которая была использована.
> Дополните репозиторий и напишите инструкцию в readme.
> Спасибо.

Добавил requirements.txt, написал инструкцию в readme, настроил запуск в докере с демо данными и пользователем админ.
